### PR TITLE
Dimensioncollapse

### PR DESCRIPTION
**Pull request by agibsonccc**
Adds dimension collapse algo and improves tests.

### CODE REVIEW

**Comment by saudet** [comment]
FYI,  the "-march" option doesn't exist with the PPC version of GCC. That's why I removed it when building for that platform.

**Comment by agibsonccc** [comment]
@saudet you're welcome to add it back. I reverted to the last known good version of cmake that built ;/

**Comment by saudet** [comment]
Ok, but it doesn't build on some machines because of `IF(${CMAKE_SYSTEM_PROCESSOR} MATCHES "ppc64*")`?

**Comment by agibsonccc** [comment]
Maybe? It wasn't generating binaries.

**Pull request merged**
