### PR TITLE
Add CHIP_EXTENSION option for "avx512", setting ARCH to "skylake-avx512"

### PR DESCRIPTION
**Pull request by saudet**
This allows us to build for AVX512 with a command such as `bash buildnativeoperations.sh -c cpu-avx512` and have the binaries placed in the "cpu-avx512" directory where they can be picked up by ND4J, see pull https://github.com/deeplearning4j/nd4j/pull/2253.

### CODE REVIEW

**Comment by saudet** [comment]
Sure, we can add more once easily, just want to make sure with one first :)

**Comment by raver119** [comment]
How do you think, can we unify that with `-a` key? So, instead of `-a native` we could use say `-a avx512`?

**Comment by raver119** [comment]
As in: someone specifies: `-a avx512`; and build script includes all viable sets up to specified: sse, avx, avx2, fma, avx512?

**Comment by saudet** [comment]
AVX512 isn't an "architecture"... I was thinking about adding an "extension" option instead of using the "chip" one actually. Would that be better?

**Comment by saudet** [comment]
Or we could go with specifying an architecture with the extension like "-a x86_64-avx512", or use the platform option, which can also work for cross-compiling like "-platform android-x86_64-avx2". What do you think?

**Comment by raver119** [comment]
Right now `-a` used only for march/mtune switch, just to get `-a native` working, so as long as we can compile binariers for specific instruction sets - i'm happy.

**Comment by saudet** [comment]
Setting the architecture isn't the issue, it's passing multiple differently compiled binaries to JavaCPP extensions in ND4J. In the end, I figured that using the "platform" option would be confusing because we can't use it that way in JavaCPP. It would start looking for "avx512" artifacts for all dependencies, for example. So, I've just added a CHIP_EXTENSION option, which also gets set when the user passes "avx512" for the arch option instead.

**Pull request merged**
