### PR TITLE
Get rid of macOS hack

### PR DESCRIPTION
**Pull request by raver119**
This PR gets rid of macos specific compilation hack for gcc-7 used for a while, and became useless now.

### CODE REVIEW

**Comment by saudet** [comment]
No, we need to leave this "hack" or it won't build with old versions of Xcode that are required by CUDA. You'll probably check notifications from @sshepel about failing builds on Mac now...

**Comment by raver119** [comment]
Ouch, but i've ensured there's no issues on Jenkins... Let's revert it then for now?

**Comment by raver119** [comment]
http://master-jenkins.skymind.io:8080/blue/organizations/jenkins/deeplearning4j%2Flibnd4j/detail/PR-827/1/pipeline

**Comment by sshepel** [comment]
@saudet looks good on Jenkins for now, lets wait a while :)

**Pull request merged**
