### PR TITLE
Update macOSx10 (CPU only).md

### PR DESCRIPTION
**Pull request by chrismattmann**
- formatting and use 8.0 Cuda project (7.5 not in master anymore).

### CODE REVIEW

**Comment by agibsonccc** [comment]
@chrismattmann actually we do have nd4j-cuda-7.5. nd4j-cuda is just the same code base linked against different cuda versions: http://search.maven.org/#search%7Cga%7C1%7Cnd4j-cuda

**Comment by chrismattmann** [comment]
got it. Well that doesn't compile when you check out from master. It is looking for 8.0. It's also missing the -platform one. Here is the command I got it to build on Mac with:

`mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-8.0,!org.nd4j:nd4j-tests,!org.nd4j:nd4j-cuda-8.0-platform'`

**Comment by chrismattmann** [comment]
Found this out by trying to build dl4j since Maven builds are down cf. https://github.com/apache/tika/pull/165

**Comment by agibsonccc** [comment]
@chrismattmann Did you run the setuposx.sh? If you do that, compile cpu with ./buildnativeoperations.sh and then set the LIBND4J_HOME followed by building nd4j (minus cuda)
 you should be fine.

**Comment by chrismattmann** [comment]
I did that already @agibsonccc followed that exact guide. It still tried to build cuda.

**Comment by agibsonccc** [comment]
This used to work (from our windows instructions):
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-7.5,!org.nd4j:nd4j-cuda-7.5-platform,!org.nd4j:nd4j-tests'


I wonder what would be different now?

**Comment by chrismattmann** [comment]
well the first difference is:

 1. that's not included in your mac instructions (which this PR updates) specifically the part about *-platform reactor exclusion 👍 
 2. if you build from master it's 8.0, so the version in the guides need bumping.

**Comment by agibsonccc** [comment]
k thanks for the clarification! (sorry you're talking to someone in a linux bubble :D this was educational)

**Comment by chrismattmann** [comment]
hehe thanks @agibsonccc I'm a Linux fan, but currently Mac challenged ;) Thanks for the merge 👍 hopefully it helps other Mac'ers

**Pull request merged**
