### PR TITLE
Revert "Add numpy serialization"

### PR DESCRIPTION
**Pull request by huitseeker**
Reverts deeplearning4j/libnd4j#369

See https://github.com/deeplearning4j/libnd4j/issues/370 https://github.com/deeplearning4j/libnd4j/issues/371

### CODE REVIEW

**Comment by raver119** [comment]
Why revert? If there's zlib.h being missing, why not just install it? It's either in zlib-devel, or zlib1g-dev depending on distribution. Your fail log looks like rhel/centos based, and rhel should have zlib-devel available as well, it just can't be missing in repos.

**Comment by raver119** [comment]
p.s. Sure, we just need to mention new dep in libnd4j README.md now.

**Comment by huitseeker** [comment]
@raver119 I have bisected the previous commit as passing on the same docker image, no install necessary.

**Comment by huitseeker** [comment]
@raver119 and on the website, in install. And on https://github.com/deeplearning4j/java_deps

Given #370 should we also state we require gcc >= 5.3.1 ?

**Comment by raver119** [comment]
I'm looking into it right at this moment. Just finished compilation with 5.4.0 though :/

**Comment by raver119** [comment]
Same issue as #370 with gcc 5.4.0

**Comment by raver119** [comment]
Fix for #370 was applied, please check it out and confirm it works for you as well.

**Comment by agibsonccc** [comment]
Not agreeing with this here. There's no reason to revert it.

**Pull request closed without merging**
